apiVersion: 'v1'
kind: 'PersistentVolume'
metadata:
  name: 'mysql-pv'
spec:
  capacity:
    storage: '5Gi'
  accessModes:
    - ReadWriteMany  
  hostPath:
    path: '/home/hasher/K8s/python-app/data'

---

apiVersion: 'v1'
kind: PersistentVolumeClaim
metadata:
  name: 'mysql-pvc'
spec:
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: '5Gi'
