apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pythonapp-deployment
spec:
   replicas: 2
   selector:
      matchLabels:
        app: frontend
   template:
     metadata:
       labels:
         app: frontend
     spec: 
       containers:
       - name: python-app-container
         image: harshvardhan03/sample-python-with-db:v1
         ports:
           - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5000
      nodePort: 30002

